language: node_js
sudo: false
# force trusty as Google Chrome addon is not supported on Precise
dist: trusty
node_js:
  - "6.9.1"
# addons:
#   apt:
#     sources:
#       - google-chrome
#     packages:
#       - google-chrome-stable
#  firefox: "38.0"
  #apt:
    #sources:
      # needed to install g++ that is used by npms's native modules
      #- ubuntu-toolchain-r-test
    #packages:
      # needed to install g++ that is used by npms's native modules
      #- g++-4.8
  # https://docs.travis-ci.com/user/jwt
  #jwt:
    # SAUCE_ACCESS_KEY<=secret for NGBUILDS_IO_KEY to work around travis-ci/travis-ci#7223, unencrypted value in valentine as NGBUILDS_IO_KEY>
    # we alias NGBUILDS_IO_KEY to $SAUCE_ACCESS_KEY in env.sh and set the SAUCE_ACCESS_KEY there
    #- secure: "L7nrZwkAtFtYrP2DykPXgZvEKjkv0J/TwQ/r2QGxFTaBq4VZn+2Dw0YS7uCxoMqYzDwH0aAOqxoutibVpk8Z/16nE3tNmU5RzltMd6Xmt3qU2f/JDQLMo6PSlBodnjOUsDHJgmtrcbjhqrx/znA237BkNUu6UZRT7mxhXIZpn0U="
cache:
  directories:
    - ./.chrome/chromium
install:
  - npm install
script:
  - npm run test:travis
  # Excluding build process as of now
  #- npm run build
after_success: 'npm run coveralls'